export const PrivacyText = {
  text1: `By visiting Buslala platforms ("Website, Mobile site and Mobile Apps"), you are accepting and consenting to the practices described in this Privacy Notice (as defined here in after). This document describes the privacy policy ("Privacy Notice") of Buslala Technologies Pvt Ltd. ("Buslala" or "we" or "us" or "our") and is designed to explain registered users of the Website, Mobile site and Mobile App, Mobile site and Mobile App including(without limitation) buyers of bus tickets, customers who are using our bus partners, bus ticket booking agents, intermediaries who sell services on the Website, Mobile site and Mobile App, other users/visitors of the Website, Mobile site and Mobile Apps ("you" or "your" or "yourself" or "user") what data/information we collect, why we collect it, and what we do with it. Your use of and access to the Website, Mobile site and Mobile App and the services provided through (i) the Website, Mobile site and Mobile App and (ii) mobile site, mobile app and other offline channels including call centers and offices ("Other Interfaces") are subject to this Privacy Notice and our Terms and Conditions. Any capitalized term used but not defined in this Privacy Notice shall have the meaning attributed to it in our Terms and Conditions.`,

  text2: `This Privacy Notice is applicable all persons including persons/entities who purchase, intend to purchase or inquire about service(s) made available by Buslala through the Website, Mobile site and Mobile App and Other Interfaces (collectively "Services"). If you disagree with any provision contained in this Privacy Notice, then please do not (i) use or access the Website, Mobile site and Mobile App or Other Interfaces or (ii) avail any of the Services. By using or accessing the Website, Mobile site and Mobile App or Other Interfaces, the User hereby agrees with the Privacy Policy in its entirety and the contents here in.`,
  text3: `Ans: Booking a bus ticket online in India is easy with BUSLALA Mobile Application or website. Simply enter the FROM (Source) – TO (destination) details along with the date you wish to travel in the bus search option on Mobile application or site. Within seconds you will be given a list of buses availability for your route. Select your bus that suits you best for you. Then just follow the simple steps to the ticket booking (Maximum Two Seat will book in one time and if you need more than two then you can follow same process) and please provide name & e-mail as you mentioned in passenger details then payment process and your seat will be reserved for your bus journey. We advise you to book your tickets at least Six hours before scheduled departure. After you purchase your ticket you will receive an email confirmation that also serves as your boarding pass for most of the bus partners. We don't oversell our schedules, so this boarding pass will guarantee you a seat on your ticketed schedule.
  `,
  text4: `Ans: We'll make every effort to ensure that your travel is not affected by providing alternate services to help you reach the destination.`,
  text5: `Ans: Buslala does not charge anything extra when compared to the traditional way (offline). The tickets are absolutely at the same cost that the travel bus partner has priced them.`,
  text6: `Ans: Please arrive at the pick-up point a minimum of 25 minutes before departure. Please have your SMS confirmation (or ticket printout in some cases) and government issues personal identification ready while boarding.
  `,
  text7: `Ans: There is more than one reason for this: 1. Some Bus Partners/buses have AC/Non-AC in the same bus. 2. Some buses have Seater and Sleeper type seats in the same bus. 3. Some Bus Partners want to price the front rows a little higher than the back rows in the bus.`,
  text8: `Ans: A copy of the ticket would have been sent to you by E-mail & SMS when you booked the ticket. Please take a printout of that mail and produce it at the time of boarding. If you have not received your ticket to the e-mail id you provided, you can take a screenshot of your ticket which is in booking details in Buslala mobile application or website.`,
  text9: `Ans: You must fill in the field "Mobile Number" when booking tickets. Your mobile number will be used to send Booking confirmation SMS, Boarding point details, bus partner will be able to contact you quickly in case you are not on time at the boarding point or Buslala will be able to contact you if there is any change in schedule or vehicle or breakdown.`,
  text10: `Ans: If you did not receive an email after your conformation of the booking, there can be two reasons: The electronic credit card or debit payment has failed. In this case the purchase is cancelled by the system. You have entered an incorrect e-mail address. Please check your bank statement first to see if your account/card was charged, please contact us via e-mail(care@buslala.com) or call +91 90-31-90 1444) to solve this problem. If your account was not charged, then you can retry the booking. If you have any further questions, please feel free to call our 24/7 customer support.`,
  text12: `Ans: Yes. Please contact our 24/7 customer support and we will be able to re-send you the SMS ticket confirmation with booking details.`,
  text13: `Ans: Yes. It is mandatory to carry government issued identity proofs along with your e-ticket.`,
  text14: `Ans: Yes. The tickets booked through Buslala can be cancelled* before the cut off time on the day of journey which is the start of the bus at the first boarding point. *Cancellation terms vary from bus partner to bus partner.`,
  text15: `Ans: To cancel your ticket, visit the Cancellation page and proceed for cancellation. Check the refund terms before cancellation. These terms are also shown at the time of booking, while you are selecting the particular bus. These terms are also available on the ticket printout. Please check these terms before you confirm your cancellation.`,
  text16: `Ans: Partial Ticket Cancellation is accepted by few bus partners. Please check the cancellation terms of the bus partner provided while booking the ticket. Partial Cancellation of ticket is currently allowed through our portal. Please visit `,
  text17: `Ans: We accept Internet banking, UPI, Payment via Debit Cards (Visa, MasterCard, American Express and Maestro Cards). We accept cards that are issued in India only.`,
  text18: `Ans: Yes, you can call to +91 90-31-90 1444 and book your seat once payment done via Phonepe/Google pay/Paytm.`,
  text19: `Ans: Transactions on Buslala.com are very safe. Buslala.com has the best-in-class security. Buslala.com uses Secure Socket Layers (SSL) data encryption. Using SSL ensures that the information exchanged with Buslala.com is never transmitted unencrypted thus protecting the information from being viewed by unauthorized individuals. This encryption is done using 256-bit RC4 encryption. Payment information is processed over secure gateways which are certified by Visa and MasterCard.
  `,
  text20: `Ans: Yes, you can pay/book bus tickets for others. It is not necessary that the payee has to travel. Please make sure you are giving the right details for all passengers and also make sure they carry the Govt. issued ID cards to ensure that there won't be any issues.`,
  text21: `Ans: Yes, You can book your bus tickets by phone call on +91 90-31-90 1444.`,
  text22: `Ans: No. We do not have that facility for now. You can either carry the SMS confirmation we send or in some cases you can carry the ticket printout that you can print after booking confirmation.`,
  text23: `Ans: Payment for any booking, after selecting the seats has to be completed within 10 minutes. If you don't complete the payment during the 10 minutes after selecting your seats, your order will be annulled/void and the seats will be released for others to book.`,
  text24: `Ans: Buslala provides 100% refund if the bus is missed due to either Buslala or its partner company's fault. However, if the bus is missed due to any other reasons not directly related to Buslala it does not provide any refund (for example: waiting at the wrong pickup point or arriving late at the pickup point is not considered for refund).`,
  text25: `Ans: Generally all refunds are processed the same day in most cases. Money is transferred/refunded back to the passenger's debit card/Bank account or UPI by the payment gateway within 24 hours. After which depending on the customer's bank, it takes 2-7 working days to reflect the credit in your account.`,
  text26: `Ans: Full refund happens only when there has been an error from Buslala's end or the bus partners end. In other cases, where the traveller requests for cancellation, partial refund happens. Please check the cancellation terms these are mentioned on the ticket printout/Email. Or please contact our customer support for more details.`,
  text27: `Ans: Every Bus Partner has their own rules regarding amount of luggage allowed, available luggage space, extra payments for boxes, etc. Please feel free to call our 24/7 customer support if you need any specific information.`,
  text28: `Ans: If you have any additional questions, comments or other general customer service inquiries, please email us at care@buslala.com or call us at +91 90-31-90 1444.`,
  text29: `Buslala.com (Buslala Technologies Pvt. Ltd.) provides a technology platform for online bus ticketing that connects intending travellers with bus partners. Buslala does not own or operate or offer the services of transportation to the user. Buslala also doesn’t act as an agent of any bus partner in the process of providing the above-mentioned technology platform services.
  Buslala acts as a marketplace facilitating booking of bus tickets and therefore, neither influences nor controls the booking flow, scheduling/rescheduling, confirmation to confirmed, cancellations or other changes to the delivery timelines or other related aspects of the bus ticket, delays, berth preferences or any other lack or deficiency of services. Buslala is merely a platform to search for desired bus tickets to be booked through Buslala app or site.
  `,
  text30: `(a)We receive and store any information you enter on our Website, Mobile site and Mobile App or give us in any other way. In general, you can browse the Website, Mobile site and Mobile App without telling us who you are or revealing any personal information about you. Once you give us your personal information, you are not anonymous to us.

  (b)We collect personally identifiable information (email address, other addresses, name, phone number, gender, travel preferences, travel plan details bookings/preferences, telephone (mobile or otherwise) from you when you register and create an account with us, and that you provide to us from time to time. The information may also include information such as your banking details (including UPI/Net banking/Debit card) and any other information relating to your income and/or lifestyle; billing information, payment history etc. (as shared by you).
  `,
  text31: `(c)Further, we may collect certain other information, including (without limitation) the following information, while you (i) use the Website, Mobile site and Mobile App and/or (ii) access service made available by Buslala through the Website, Mobile site and Mobile App and Other Interfaces:

  (i)data either created by you or by a third party and which you wish to store on our servers such as image files, documents etc.;
  (ii)transactional history (other than banking details) about your e-commerce activities, buying behaviour on the Website, Mobile site and Mobile App and Other Interfaces;
  (iii)user name, password, email address and other security-related information used by you in relation to the Services;
  (iv)data available in public domain or received from any third party including social media networks, including but not limited to personal or non-personal information from your linked social media networks as a part of your account information and
  (v)information pertaining to persons(s)/traveller(s) for whom booking are made through the Website, Mobile site and Mobile App and Other Interfaces.
  
  (d)Such information collected by us may include information considered to be ‘sensitive personal information’ of the user under the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 ("SPI Rules").Such ‘sensitive personal information’ generally includes user’s information relating to password, financial information such as bank account or debit card or UPI or other payment instrument details, physical, physiological and mental health condition, sexual orientation, medical records and history, and biometric information. Further, the SPI Rules require your express consent to collect, store and use such personally identifiable information collected by us. You hereby consent to such use, collection, storage and disclosure of ‘sensitive personal information’ by us in accordance with this Privacy Notice as required under applicable law.
  
  (e)Where possible, we indicate the fields which are required and the fields which are optional. You [always] have the option to not provide information by choosing not to use a particular service or feature on the Website, Mobile site and Mobile App. You [always] have the option to withdraw your consent, upon which we have the option not to provide services for which the consent was sought.
  
  (f)In case you are booking bus tickets on the Website, Mobile site and Mobile App and/or through Other Interfaces for and/or on behalf of other persons, you here by confirm and represent that each of such other person(s)/traveller(s) for whom a booking has been made, has agreed to the information shared by you disclosed to us and further be shared by us with the concerned service provider(s).
  
  (g)While making a booking, we may use ‘sensitive personal information’ including, payment details which include card holder name, debit card number (in encrypted form)/UPI id/net banking id & password with an expiration date, banking details, wallet details etc., as shared and allowed to be stored by you. We may also use the information of travellers list as available in or linked with your account. This information is presented to the user at the time of making a booking to enable you to complete your bookings expeditiously. Further, we may use your ‘sensitive personal information’ to provide seamless and convenient services and such uses will include (without limitation) (i) confirmation of your reservations/bookings with you and respective service providers, (ii) informing of the transaction status,(iii) communicating booking confirmations either via electronic means or other messaging service, (iv) communicating any updates or changes to your booking(s), (v) enabling customer service team to contact you, if necessary,(vi) customize the content of the Website, Mobile site and Mobile App and other Interfaces; (vii) request for reviews of the Services or any other improvements; (viii) sending verification message(s) or email(s), (ix)validating/authenticating your account and to prevent any misuse or abuse and (x)contact you to offer offers. Further to the above, your information will be shared with the end service providers like bus service providers or any other suppliers who are responsible for fulfilling your booking. We may employ other companies and individuals to perform functions on our behalf (including but not limited to payment processing, data hosting, and data processing platforms). We may also share certain information to our corporate affiliates or business partners who may contact the customers to offer certain products or services, which may include free or paid products/services (like travel insurance, discount coupons, entertainment services), which will enable the customer to have better travel experience or to avail certain benefits specially made for Buslala customers. We may provide anonymous statistical information based on this data to suppliers, advertisers, affiliates and other current and potential business partners. You may note that while making a booking with Buslala you authorize us to share your information with the said service providers and suppliers. Buslala does not authorize the end service provider to use your information for any other purpose(s) except as may be for fulfilling their part of service. Nevertheless, the information shared with such service providers/suppliers is beyond the purview and control of Buslala, and hence we are not accountable for any unauthorized use of such information by any service provider/supplier. You are therefore advised to review the privacy policies of the respective service provider or supplier whose services you choose to avail.
  
  (h)We may share user information with entities that control, are controlled by or are under the common control with Buslala and that are either subject to this Privacy Notice or follow practices at least as protective as those described in this Privacy Notice. Further, we may share user information with our affiliates or associate entities. If the assets and/or business of Buslala are acquired, our customer information may also be transferred to the acquirer depending up on the nature of such acquisition. In addition, as part of business expansion/development/restructuring or for any other reason whatsoever, if we decide to sell/transfer/assign our business, any part thereof, any of our subsidiaries or any business units, then as part of such restructuring exercise customer information including the personal information collected here in shall be transferred accordingly.
  
  (i)We use non-identifiable information in aggregate or anonymized form to build higher quality, more useful online services by performing statistical analysis of the collective characteristics and behaviour of our customers and visitors.
    
  (j)We receive and store certain types of information whenever you interact with us. We may also receive/store information about your location and your mobile device, including a unique identifier for your device. We may use this information for internal analysis and provide you with location-based services, such as search results and other personalized content. We may automatically track certain information about you based upon your behaviour on our Website, Mobile site and Mobile App. We use this information to do internal research on our users’ demographics, interests, and behaviour to better understand, protect and serve you. This information is compiled and analysed on an aggregated basis. This information may include your login, e-mail address, password, computer and connection information such as browser type and version, operating system and platform, transaction history, which we sometimes aggregate with similar information from other customers to create customized or additional features, the full uniform resource locators (URL) click stream to, through and from our Website, Mobile site and Mobile App (including date and time), cookie number, travel routes, service providers, bus partners you viewed or searched for, and any phone number used to call our customer service number.
  
  (k)We may also use browser data such as cookies, flash cookies (also known as ‘flash local shared objects’), or similar data on certain parts of our Website, Mobile site and Mobile App for fraud prevention and other purposes. During some visits, we may use software tools such as JavaScript to measure and collect session information, including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page.
  
  (l)If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback, we will collect that information you provide to us. We retain this information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law.
  
  (m)We might receive information about you from other sources and add it to our account information. If other users or third parties send us correspondence about your activities, we may collect such information into a file specific to you.
  
  (n)We release account and other personal information when we believe release is appropriate to comply with the law, enforce or apply our Terms and Conditions and other agreements, or protect the rights, property or safety of Buslala, our users or others. This includes exchanging information with other companies, organisations, government or regulatory authorities for fraud protection and credit risk reduction. However, this does not include selling, renting, sharing or otherwise disclosing personally identifiable information from customers for commercial purposes in a way that is contrary to our commitments under this Privacy Notice.
  
  (o)In addition to the circumstances described above, Buslala may disclose the information if required to do so by law, required by any enforcement authority for investigation, required by court order or in reference to any legal process and regulatory, required for internal compliance and audit exercise or required for protecting the rights and business of Buslala.
  
  (p)Other than as set out above, you will receive notice when information about you might go to third parties and you will have an opportunity to choose not to share the information. Whenever we transfer personal information to countries outside India in the course of sharing information as set out above, we will ensure that the information is transferred in accordance with this Privacy Notice and as permitted by the applicable laws including but not limited to Information Technology Act, 2000 and the rules framed there under.`,
  text32: `a)Device and App History: We need your device permission to get information about your device, like OS(operating system) name, OS version, mobile network, hardware model, unique device identifier, preferred language, etc. Basis these inputs, we intend to optimize your travel booking experience.

  b)Identity: This permission enable us to know about details of your account(s) on your mobile device. We use this info to auto-fill your email ID’s and provide a typing free experience. It also helps us map email ID’s to a particular user to give you the benefit of exclusive travel offers, wallet cashbacks, etc. It also allows facilitating your Facebook and Google+ login.
  
  c)Location: This permission enables us to give you the benefit of location-specific deals and provide you with a personalized experience. When you launch Buslala app to make a travel booking, We also require this permission to be able to help you track your bus with respect to your location.
  
  d)SMS: If you allow us to access your SMS, we read your SMS to autofill or prepopulate ‘OTP’ while making a transaction and to validate your mobile number. This provides you with a seamless purchase experience while making a booking and you don’t need to move out of the app to read the SMS and then enter it in the app.
  
  e)Phone: The app requires access to make phone calls so that you can make phone calls to our customer care directly through the app.
  
  f)Contacts: If you allow us to access your contacts, it enables us to provide a lot of social features to you such as sharing tickets or location with your friends. This permission also allows you to select numbers from your contacts for mobile recharges done on the app.
  
  g)Photo/Media/ Files: The libraries in the app use these permissions to allow users to save and upload multimedia reviews.
  
  h)Wi-Fi connection information: When you allow us permission to detect your Wi-Fi connection, we optimize your band width usage for multimedia uploads.
  
  i)Device ID and Call information: This permission is used to detect your Android ID through which we can uniquely identify users. It also lets us know your contact details using which we pre-populate specific fields to ensure a seamless booking experience.
  
  j)Camera: This permission is used to capture pictures of the boarding point or bus before the journey. This image can be uploaded as part of multimedia reviews.
  
  k)Calendar: This permission enable us to put your travel plans on your calendar.
  IOS PERMISSIONS:
  a)Notifications: If you opt-in for notifications, it enables us to send across exclusive deals, promotional offers, travel related updates, etc. on your device. If you do not opt for this, updates for your travel like booking confirmation, a refund (in case of cancellation), etc. will be sent through SMS.
  
  b)Contacts: This permission enables us to know about the details of your account(s) on your mobile device. We use this info to auto-fill your email ID’s and provide a typing free experience. It also helps us map email ID’s to a particular user to give you the benefit of exclusive travel offers, wallet cashbacks, etc. It also allows facilitating your Facebook and Google+ login.
  
  c)Location: This permission enables us to give you the benefit of location-specific deals and provide you with a personalized experience. When you launch Buslala app to make a travel booking, we detect your location so that your nearest city is auto-filled. We also require this permission to be able to help you track your bus with respect to your location.
  
  d)Photo/Media/ Files: The libraries in the app use these permissions to allow users to save and upload multimedia reviews.
  
  e)Camera: This permission is used to capture pictures of the boarding point or bus before the journey. This image can be uploaded as part of multimedia reviews.
  
  f)Calendar: This permission enables us to put your travel plans on your calendar.
  `,
  text33: `1.A ‘cookie’ is a small piece of information stored by a web server on a web browser so it can be later read back from that browser. Cookies are useful for enabling the browser to remember information specific to a given user. We place both permanent and temporary cookies in your computer’s hard drive.

  2.We use data collection devices such as ‘cookies’ on certain pages of the Website, Mobile site and Mobile App to help analyse our web page flow, measure promotional effectiveness, and promote trust and safety. We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies", meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits, although in that case, you may not be able to use certain features on the Website, Mobile site and Mobile App and you may be required to re-enter your password more frequently during a session.
  
  3.Additionally, you may encounter "cookies" or other similar devices on certain pages of the Website, Mobile site and Mobile App that are placed by third parties. We do not control the use of cookies by third parties.
  `,
  text34: `1.We strive to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you input in addition to maintaining the security of your information as per the International Standard IS/ISO/IEC 27001 on "Information Technology Security Techniques Information Security Management System-Requirements".

  2.This means all Personal Information you provide is transmitted using TLS (Transport Layer Security) encryption. TSL is a proven coding system that lets your browser automatically encrypt, or scramble, data before you send it to us. Website, Mobile site and Mobile Apps has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.
  
  3.We maintain physical, electronic and procedural safe guards in connection with the collection, storage and dis closure of personal information (including sensitive personal information). Our security procedures mean that we may occasionally request proof of identity before we disclose personal information to you.
  
  4.It is imperative that you have measures to safeguard against unauthorised access to your password and to your computer. Please ensure that you read and understand the terms and conditions which are set out in the Conditions of Use, in this regard.
  `,
  text35: `Use of the Website, Mobile site and Mobile Apps is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor, i.e., under the age of 18 years, or do not have the capacity to enter into a legally binding contract, you may use the Website, Mobile site and Mobile Apps only with the involvement of a parent, guardian or a duly authorised person.`,
  text36: `1.As mentioned above, you can choose not to provide information, even though it might be needed to make proper use of the Services or to take advantage of some of the features offered through the Website, Mobile site and Mobile Apps.

  2.You can add or update certain information on some of the pages of the Website, Mobile site and Mobile Apps, such as your profile. When you update information, we usually keep a copy of the previous version for our records.
  
  3.If you do not want to receive e-mail or other mail from us, you will be free to adjust your preferences to reflect the same. However, even in case you do not want to receive Conditions of Use and other legal notices from us, such as this Privacy Notice, all those notices will still govern your use of Website, Mobile site and Mobile Apps and requests placed with us, and it is your responsibility to review them for changes.
  `,
  text37: `1.Our business operations and our business are bound to change constantly, and so our Privacy Notice and the Conditions of Use will change also. We may e-mail periodic reminders of our notices and conditions unless you have instructed us not to, but you should check our Website, Mobile site and Mobile Apps frequently to see recent changes.

  2.Unless stated otherwise, our current Privacy Notice applies to all information that we have about you and your account. By using or continuing to use the Website, Mobile site and Mobile Apps you agree to our use of your information (including sensitive personal information) in accordance with this Privacy Notice, as may be amended from time to time by Buslala at its sole discretion. You also agree and consent to us collecting, storing, processing, transferring and sharing information (including sensitive personal information) related to you with third parties or service providers for the purposes as set out in this Privacy Notice.
  
  3.If you have any concern about privacy or grievances regarding the Website, Mobile site and Mobile Apps, please email us at care@buslala.com with a detailed description and we will endeavour to resolve the issue for you.
  
  
  BY VISITING OUR WEBSITE, MOBILE SITE AND MOBILE APPS AND/OR BY USING THE SERVICES OR BY OTHER WISE GIVING US YOUR INFORMATION, YOU WILL BE DEEMED TO HAVE READ, UNDERSTOOD AND AGREED TO THE PRACTICES AND POLICIES OUTLINED IN THIS PRIVACY NOTICE AND AGREE TO BE BOUND BY THE PRIVACY NOTICE. YOU HERE BY CONSENT TO OUR COLLECTION, USE AND SHARING, DISCLOSURE OF YOUR INFORMATION AS DESCRIBED IN THIS PRIVACY NOTICE. WE RESERVE THE RIGHT TO CHANGE, MODIFY, ADD OR DELETE PORTIONS OF THE TERMS OF THIS PRIVACY NOTICE, AT OUR SOLE DISCRETION, AT ANY TIME. IF YOU DO NOT AGREE WITH THIS PRIVACY NOTICE AT ANY TIME, DO NOT USE ANY OF THE SERVICES OR GIVE US ANY OF YOUR INFORMATION. IF YOU USE THE SERVICES ON BEHALF OF SOME ONE ELSE (SUCH AS YOUR CHILD) OR AN ENTITY (SUCH AS YOUR EMPLOYER), YOU REPRESENT THAT YOU ARE AUTHORISED BY SUCH INDIVIDUAL OR ENTITY TO (I) ACCEPT THIS PRIVACY NOTICE ON SUCH INDIVIDUAL’S OR ENTITY’S BEHALF, AND(II) CONSENT ON BEHALF OF SUCH INDIVIDUAL OR ENTITY TO OUR COLLECTION, USE AND DISCLOSURE OF SUCH INDIVIDUAL’S OR ENTITY’S INFORMATION AS DESCRIBED IN THIS PRIVACY NOTICE.
  `,
  text38: `1. Buslala.com (Buslala Technologies Pvt Ltd.) provides a technology platform for online bus ticketing that connects intending travellers with bus operators. Buslala does not own or operate or offer the services of transportation to the user. Buslala also doesn't act as an agent of any bus operator in the process of providing the above-mentioned technology platform services.
  2. The arrival and departure times mentioned on the ticket are only tentative timings. Buses may be delayed due to some unavoidable reasons like traffic jams etc. However, the bus will not leave the source before the time that is mentioned on the ticket. Passengers are advised to call the bus operator contact number mentioned in the ticket and reconfirm the boarding point location and departure time on the day of journey.
  3. Passengers are required to furnish the following details at the time of boarding the bus. Failing to do so, they may not be allowed to board the bus. 3.1. SMS of the ticket or Email. (This is widely accepted by most bus operators) 3.2. Some operators do not accept the electronic ticket formats. We provide the details of such operators while booking tickets on Buslala.com. In such case we request you to kindly carry a printout of the ticket. 3.3. Proof of Identity (Driving License or Aadhar Card or Passport or PAN Card or Voter Card)
  4. Buslala Ultimate and Assured classification of Bus Operators is done from time-to-time based on Customer's Feedback and Surveys conducted by Buslala. Buslala is showing the classification for customers to make an informed decision while choosing a Bus Operator for their journey. The choice of the bus operator is purely at the discretion of the customer. The classification of Bus Operator might change depending on the service performance of bus operator.
  5. The passengers should reach at the mentioned boarding points 25 minutes prior to the scheduled departure time.
  6. Any complaints/grievances should be reported within 48 hrs from date of journey performed.
  7. A booking is considered confirmed if the booking confirmation page is shown to the customer, even if SMS/Email fails to deliver for any reason.
  8. If ticket confirmation/cancellation, SMS/Email, is not sent for any reason, if reported it can be resent by our support team. SMS/Email might fail to deliver or get delayed for several reasons which are not in Buslala’s control.
  9. Payment gateway/service charges - Buslala will not charge any additional payment gateway charge or service unless otherwise specified in the booking details page.
  10. By making a booking on Buslala.com - customer acknowledges that Buslala will Call/Email/SMS or send alerts to give/take information regarding his/her bookings.
  11. In case of any claims arising out of unforeseen consequences/exigencies, BUSLALA liability would be limited to the extent of two times the value of the booking amount.
  12. Any additional charges paid towards additional service/s like Insurance shall not be refunded if the ticket/s are cancelled.
  13. If you provide any information that is untrue, inaccurate, not current or incomplete, or Buslala has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Buslala has the right to suspend or terminate your account and refuse any and all current or future use of the Service.
  14. The terms and conditions of our services can be amended, modified or withdrawn by Buslala.com at any time without notice.
  `,
  text39: `1. Generation of a valid bus ticket through its partners/operators.
  2. Sending an SMS or Email for ticket confirmation/cancellation.
  3. Providing voice/email support for any ticket booking/cancellation/refund issues.
  `,
  text40: `1. Any incorrect data provided by customer while booking the ticket.
  2. Any Bus delays, breakdowns, vehicle exchange, service cancellations and accidents.
  3. Any misbehaviour by the operator staff or co-passenger.
  4. Loss/damage of baggage.
  5. Late arrival by customer at the boarding point.
  6. Customer phone not reachable, operator did not call at the boarding point and left without picking the customer.
  7. Customer waiting at wrong boarding point.
  8. Any change of seat numbers or bus number done by the bus operator manually.
  9. Operator changing the boarding point for any reason.
  10. Operator arranging a different vehicle for pickup at boarding point and boarding the actual vehicle at a different place.
  11. Improper booking done by agent, please contact the agent directly.
  12. Operator not providing In-bus amenities/facilities mentioned while booking.
  13. Change of bus type by Bus operator for any reason.
  14. Bus fares are not controlled by Buslala, so any change in fares is not the responsibility of Buslala.
  15. The fare might vary based on the seat selected. So the fare shown in the "Search Page" and "Seat Selection Page" might vary. For Govt. Bus Operator's Bookings, Total fare is calculated as per the Govt. Rules after entering the passenger's age.
  16. The rules and regulations for carrying luggage vary among bus operators. Most of the operators allow 15-20 Kgs of luggage (Bags, Suitcases) per passenger. Bus Operator has sole discretion to allow passengers to carry any other form of luggage like carton boxes etc. Buslala is not responsible in case passenger is not allowed to board the bus if the luggage is inappropriate (valuable goods, explosives, carton boxes etc) to carry in the bus. Please check with bus operator directly in case any extra luggage/carton boxes etc are being carried.
  `,
  text41: `1. A transaction might fail for several reasons and your account/card might be debited without generating a ticket. If the amount is deducted from your account/card, we request you to call our customer care number to re-confirm the failed transaction before proceeding with a fresh transaction/booking.
  2. Transactions such as these are refunded back to customer. Please read the refund policy below.`,
  text42: `1. The cancellation terms are different for each bus operator and are set by the bus operator itself. These terms are shown while booking as well as on the ticket printout/Email confirmation.
  2. The cut-off time for cancelling a bus ticket depends on either bus start time/boarding point time/bus origin start time. For example: If the bus is scheduled to start from Origin Place at 4 PM and scheduled to reach your en-route selected city at 8 PM and scheduled to reach your selected boarding point at 8:15 PM then the Bus Origin Start Time is 4 PM, Bus Start Time is 8 PM and Boarding Point Time is 8:15 PM.
  3. Please read the cancellation terms provided in the search page against each bus service.
  4. Tickets booked online should be cancelled online only.
  5.Buslala.com will charge Rs.15 as a cancellation fee other than what the bus operator charges for every seat cancelled.
  6. Cancellation charges are applicable on original fare but not on the discounted fare. The cancellation charges are deducted from the collected/discounted fare and the balance is refunded. [For example: If the original ticket fare is Rs.1000 and your discounted fare is Rs.900, the cancellation charges are calculated on the original fare. i.e., on Rs.1000. So if the cancellation charges are 10%, your refund amount would be Rs.900-100 - 15 = Rs.785.]
  7. Some of the operators accept Partial Cancellation. Please go through the Cancellation Terms in the Ticket.
  8. Preponement or Postponement cannot be done once ticket is confirmed.
  9. a) If service is cancelled by Bus operator for any reason, customer will get full refund within a week from the date of journey.
  10. In case of ticket cancellation, Insurance amount is non-refundable.
  11. Service Fee/GST are non-refundable for Ticket Cancellation/Service Cancellation.
  `,
  text43: `1. Refunds processed for cancelled tickets are transferred to the passenger's bank account / debit card / UPI that was used while booking the tickets.
  2. All Refunds are processed automatically upon cancellation of tickets. Your bank may take 2-7 working days to credit this amount to your account/card/UPI.
  3. In case the refund amount is not credited to your account in 7 days from the date of refund, we kindly request you to send an email to care@buslala.com along with the ticket details/order details and bank details/UPI/debit/Wallet statement (in PDF format) from the date of booking to till date. We will provide you the necessary support in crediting back the refund amount.
  4. No refund will be processed for No-Show Passengers (Passenger who do not report at the boarding point on time).
  5. Any transaction charges/Ticket Delivery charges collected shall not be refunded if the tickets are cancelled by the customer.
  6. Any additional charges paid towards additional service/s like Insurance shall not be refunded if the ticket/s are cancelled.
  7. In the event of cancellation of a bus / service trip by the bus operator, Buslala.com will assist the passenger in providing an alternative service, subject to availability. In case an alternative is not available, then Buslala.com shall be liable to the passenger only to the extent of refunding the sum paid by the passenger for the price of the ticket.
  8. Provisions/amenities like, air conditioning, or charging point or any such other services mentioned on Buslala.com are to help you to make an informed decision. Any refunds/claims due to non-functioning or un-availability of these services needs to be settled directly with the bus service provider.
  `,
  text44: `Office Address: Buslala Technologies Pvt Ltd, C/o- Pathak Yatayaaat, Goti Ghar, Sahebganj, Muzaffarpur, Bihar-843125
  Ph: +91 90-31-90 1444
  Email: care@buslala.com
  `,
};

export const CancellationText = {
  text1:
    'The cut-off time for cancelling a bus ticket depends on either bus start time/boarding point time/bus origin start time. For example: If the bus is scheduled to start from Origin Place at 4 PM and scheduled to reach your en-route selected city at 8 PM and scheduled to reach your selected boarding point at 8:15 PM then the Bus Origin Start Time is 4 PM, Bus Start Time is 8 PM and Boarding Point Time is 8:15 PM.',
  text2:
    ' Buslala.com will charge Rs.10 as a cancellation fee other than what the bus operator charges for every seat cancelled.',
  text3:
    '1. If you are cancelling your ticket before 24 hrs of origin start time of bus than this Cancellation charges are applicable on ticket fare. The cancellation charges are deducted from the collected fare and the balance is refunded. [For example: If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 10%, your refund amount would be Rs.1000-100 - 10= Rs.890.]',
  text4:
    '2. If your are cancelling your ticket between 24 hrs to 16 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 15%, your refund amount would be Rs.1000-150- 10= Rs.840.]',
  text5:
    '3. If your are cancelling your ticket between 16 hrs to 14 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 20%, your refund amount would be Rs.1000-200 - 10= Rs.790.]',
  text6:
    '4. If your are cancelling your ticket between 14 hrs to 12 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 25%, your refund amount would be Rs.1000-250 - 10= Rs.740.]',
  text7:
    '5. If your are cancelling your ticket between 12 hrs to 10 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 30%, your refund amount would be Rs.1000-300 - 10= Rs.690.]',
  text8:
    '6. If your are cancelling your ticket between 10 hrs to 8 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 35%, your refund amount would be Rs.1000-350 - 10= Rs.640.]',
  text9:
    '7. If your are cancelling your ticket between 8 hrs to 6 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 40%, your refund amount would be Rs.1000-400 - 10= Rs.590.]',
  text10:
    '8. If your are cancelling your ticket between 6 hrs to 5 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 45%, your refund amount would be Rs.1000-450 - 10= Rs.440.] ',
  text11:
    '9. If your are cancelling your ticket between 5 hrs to 4 hrs before origin start time then- If the ticket fare is Rs.1000, the cancellation charges are calculated on the ticket fare. i.e., on Rs.1000. So if the cancellation charges are 50%, your refund amount would be Rs.1000-500 - 10= Rs.490.]',

  text12:
    '10. If your are cancelling your ticket between 4 hrs to 0 hrs before origin start time then- Refund not allowed after cancellation.',
  text13: '',
};
